### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by c3887518** [burakoner/OKX.Api#70]
OKX.Api.OkxAddress.Default.WebSocketPublicAddress = "wss://ws.okx.com:8443/ws/v5/public";
            var subscribeToTicker = await this._okxWebSocketApiClient.Public.SubscribeToCandlesticksAsync((data) =>
            {
                Console.WriteLine("AAAA");
            }, kLineTool.InsID, OkxPeriod.OneMinute);

sometimes it can work, sometimes it show "Can't connect to the server".

it's not stable

the sam issue with ResetApiClient

I tried Chinese local net work and American Windows 2012 , both of them are not stable.
How can I solve the problem, bro.

**Comment by c3887518** [comment]
var kLine =await okxRestApiClient.Public.GetCandlesticksAsync(this.InsID, OkxPeriod.OneHour);

The RestApiClient show the error below,


HttpRequestException - An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ApiSharp.Rest.Request.<GetResponseAsync>d__21.MoveNext() in E:\Github\ApiSharp\ApiSharp\Rest\Request.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ApiSharp.RestApiClient.<GetResponseAsync>d__23`1.MoveNext() in E:\Github\ApiSharp\ApiSharp\RestApiClient.cs:line 200
  WebException - The underlying connection was closed: An unexpected error occurred on a send.
     at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
    IOException - Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
       at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
      SocketException - 远程主机强迫关闭了一个现有的连接。
         at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

**Comment by burakoner** [comment]
Hi

I've just seen this issue. Firstly you dont need to specify websocket address as below. It's already defined in library.
`OKX.Api.OkxAddress.Default.WebSocketPublicAddress = "wss://ws.okx.com:8443/ws/v5/public";`

Your problem is weird. You need to check you internet connection including proxies you connected.
Also there are some limits on websocket connection to OKX. if you subscribe multiple channels you need to obey OKX limits.

Please let me know how many connections does your tools open, and how long does it take to open all connections?
